=== csa-iot/data-model/cluster.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Connectivity Standards Alliance owns the copyright to the text and content displayed or
included in this document (including in PDF, XML files and other formats) in 
all forms of media, which copyright is protected by the copyright laws of the 
United States and by international treaties.  Full text of licensing terms 
applicable to this document can be found in the LICENSE.md file.
-->
<xs:schema targetNamespace="http://zigbee.org/zcl/clusters" xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:type="http://zigbee.org/zcl/types" xmlns:zcl="http://zigbee.org/zcl/clusters">

  <xs:import schemaLocation="type.xsd" namespace="http://zigbee.org/zcl/types" />
  <xs:import namespace="http://www.w3.org/XML/1998/namespace"
    schemaLocation="http://www.w3.org/2001/03/xml.xsd" />

  <xs:simpleType name="ClusterRole">
    <xs:restriction base="xs:string">
      <xs:enumeration value="application" />
      <xs:enumeration value="utility" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ClusterHierarchy">
    <xs:restriction base="xs:string">
      <xs:enumeration value="base" />
      <xs:enumeration value="derived" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="PrimaryTransactionType">
    <xs:restriction base="xs:unsignedByte">
      <xs:minInclusive value="1" />
      <xs:maxInclusive value="2" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="ClusterIdAlias">
    <xs:attribute name="id" type="type:ClusterId" use="required" />
    <xs:attribute name="name" type="type:NamedElement" use="required" />
  </xs:complexType>

  <xs:complexType name="ClusterIdAliasList">
    <xs:sequence>
      <xs:element name="alias" type="zcl:ClusterIdAlias" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="AbstractClassification">
    <xs:attribute name="role" type="zcl:ClusterRole" use="optional" />
    <xs:attribute name="picsCode" type="xs:string" use="required" />
    <xs:attribute name="primaryTransaction" type="zcl:PrimaryTransactionType" use="optional" default="1" />
  </xs:complexType>
  
  <xs:complexType name="Classification">
    <xs:complexContent>
      <xs:restriction base="zcl:AbstractClassification">
        <xs:attribute name="role" type="zcl:ClusterRole" use="required" />
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="DerivedClassification">
    <xs:complexContent>
      <xs:restriction base="zcl:AbstractClassification">
        <xs:attribute name="role" use="prohibited" />
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>
  

  <xs:simpleType name="TagId">
    <xs:restriction base="xs:unsignedInt">
      <xs:maxInclusive value="65535" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="Attribute">
    <xs:choice>
      <xs:element name="bitmap" type="type:BitmapDefinition" minOccurs="0" maxOccurs="1" />
      <xs:element name="restriction" type="type:RestrictionType" minOccurs="0" maxOccurs="1" />
    </xs:choice>
    <xs:attribute name="id" type="type:AttributeId" use="required" />
    <xs:attribute name="name" type="type:NamedElement" use="required" />
    <xs:attribute name="type" type="xs:string" use="required" />
    <xs:attribute name="readable" type="xs:boolean" default="true" />
    <xs:attribute name="writable" type="xs:boolean" default="false" />
    <xs:attribute name="writeOptional" type="xs:boolean" default="false" />
    <xs:attribute name="writableIf" type="type:DependencyExpression" default="true" />
    <xs:attribute name="reportRequired" type="xs:boolean" default="false" />
    <xs:attribute name="sceneRequired" type="xs:boolean" default="false" />
    <xs:attribute name="required" type="xs:boolean" default="false" />
    <xs:attribute name="requiredIf" type="type:DependencyExpression" default="false" />
    <xs:attribute name="optionalIf" type="type:DependencyExpression" default="true" />
    <xs:attribute name="min" type="xs:integer" default="0" use="optional" />
    <xs:attribute name="max" type="xs:integer" use="optional" />
    <xs:attribute name="default" type="xs:string" />
    <xs:attribute name="defaultRef" type="type:NamedElement" />
    <xs:attribute name="deprecated" type="xs:boolean" use="optional" default="false" />
  </xs:complexType>
  
  <xs:complexType name="DerivedAttribute">
    <xs:choice>
      <xs:element name="restriction" type="type:RestrictionType" minOccurs="0" maxOccurs="1" />
    </xs:choice>
    <xs:attribute name="ref" type="type:NamedElement" use="required" />
    <xs:attribute name="reportRequired" type="xs:boolean" default="false" />
    <xs:attribute name="sceneRequired" type="xs:boolean" default="false" />
    <xs:attribute name="required" type="xs:boolean" default="false" />
    <xs:attribute name="requiredIf" type="type:DependencyExpression" default="false" />
    <xs:attribute name="default" type="xs:string" />
    <xs:attribute name="defaultRef" type="type:NamedElement" />
  </xs:complexType>

  <xs:complexType name="DerivedAttributeList">
    <xs:sequence>
      <xs:element name="attribute" type="zcl:DerivedAttribute" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="AttributeList">
    <xs:sequence>
      <xs:element name="attribute" type="zcl:Attribute" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Command">
    <xs:sequence>
      <xs:element name="fields" type="type:CommandFieldList" minOccurs="0" maxOccurs="1" />
      <xs:element name="tag" type="zcl:TagRef" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="id" type="type:CommandId" use="required" />
    <xs:attribute name="name" type="type:NamedElement" use="required" />
    <xs:attribute name="required" type="xs:boolean" default="false" />
    <xs:attribute name="requiredIf" type="type:DependencyExpression" default="false" />
    <xs:attribute name="optionalIf" type="type:DependencyExpression" default="true" />    
    <xs:attribute name="deprecated" type="xs:boolean" use="optional" default="false" />
  </xs:complexType>
  
  <xs:complexType name="DerivedCommand">
    <xs:sequence>
      <xs:element name="tag" type="zcl:TagRef" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>  
    <xs:attribute name="ref" type="type:NamedElement" use="required" />
    <xs:attribute name="required" type="xs:boolean" default="false" />
    <xs:attribute name="requiredIf" type="type:DependencyExpression" default="false" />        
  </xs:complexType>

  <xs:complexType name="CommandList">
    <xs:sequence>
      <xs:element name="command" type="zcl:Command" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="DerivedCommandList">
    <xs:sequence>
      <xs:element name="command" type="zcl:DerivedCommand" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ClusterSide">
    <xs:sequence>
      <xs:element name="attributes" type="zcl:AttributeList" minOccurs="0" maxOccurs="1" />
      <xs:element name="commands" type="zcl:CommandList" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute ref="xml:base" />
  </xs:complexType>
  
  <xs:complexType name="DerivedClusterSide">
    <xs:sequence>
      <xs:element name="attributes" type="zcl:DerivedAttributeList" minOccurs="0" maxOccurs="1" />
      <xs:element name="commands" type="zcl:DerivedCommandList" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Tag">
    <xs:choice>
      <xs:element name="bitmap" type="type:BitmapDefinition" minOccurs="0" maxOccurs="1" />
      <xs:element name="restriction" type="type:RestrictionType" minOccurs="0" maxOccurs="1" />
    </xs:choice>
    <xs:attribute name="id" type="zcl:TagId" use="required" />
    <xs:attribute name="name" type="type:NamedElement" use="required" />
    <xs:attribute name="type" type="xs:string" use="required" />
    <xs:attribute name="required" type="xs:boolean" default="false" />
  </xs:complexType>

  <xs:complexType name="TagList">
    <xs:sequence>
      <xs:element name="tag" type="zcl:Tag" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TagRef">
    <xs:attribute name="ref" type="type:NamedElement" use="required" />
    <xs:attribute name="required" type="xs:boolean" default="false" />
    <xs:attribute name="requiredIf" type="type:DependencyExpression" default="false" />
  </xs:complexType>

  <xs:complexType name="ClusterType">
  </xs:complexType>

  <xs:element name="cluster">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="aliases" type="zcl:ClusterIdAliasList" minOccurs="0" maxOccurs="1" />
        <xs:element name="classification" type="zcl:Classification" />
        <xs:element ref="type:type" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="server" type="zcl:ClusterSide" minOccurs="0" maxOccurs="1" />
        <xs:element name="client" type="zcl:ClusterSide" minOccurs="0" maxOccurs="1" />
        <xs:element name="tags" type="zcl:TagList" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
      <xs:attribute name="id" type="type:ClusterId" use="required" />
      <xs:attribute name="revision" type="xs:unsignedShort" use="required" />
      <xs:attribute name="name" type="type:NamedElement" use="required" />
      <xs:attribute name="manufacturer" type="type:ManufacturerId" use="optional" />
      <xs:attribute ref="xml:base" />
    </xs:complexType>
    <xs:keyref name="tagKeyRef" refer="zcl:tagKey">
      <xs:selector xpath=".//server/commands/command/tag | .//client/commands/command/tag" />
      <xs:field xpath="@ref" />
    </xs:keyref>
    <xs:key name="tagKey">
      <xs:selector xpath=".//tags/tag" />
      <xs:field xpath="@name"></xs:field>
    </xs:key>
    <xs:keyref name="defaultRef" refer="zcl:attributeKey">
      <xs:selector xpath=".//server/attributes/attribute | .//client/attributes/attribute" />
      <xs:field xpath="@defaultRef" />
    </xs:keyref>
    <xs:key name="attributeKey">
      <xs:selector xpath=".//server/attributes/attribute | .//client/attributes/attribute" />
      <xs:field xpath="@name" />
    </xs:key>
  </xs:element>
  
  <xs:element name="derivedCluster">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="aliases" type="zcl:ClusterIdAliasList" minOccurs="0" maxOccurs="1" />
        <xs:element name="classification" type="zcl:DerivedClassification" />
        <xs:element name="server" type="zcl:DerivedClusterSide" minOccurs="0" maxOccurs="1" />
        <xs:element name="client" type="zcl:DerivedClusterSide" minOccurs="0" maxOccurs="1" />      
      </xs:sequence>
      <xs:attribute name="id" type="type:ClusterId" use="required" />
      <xs:attribute name="revision" type="xs:unsignedShort" use="required" />
      <xs:attribute name="name" type="type:NamedElement" use="required" />
      <xs:attribute name="manufacturer" type="type:ManufacturerId" use="optional" />
      <xs:attribute name="inheritsFrom" type="type:NamedElement" use="required" />
      <xs:attribute ref="xml:base" />
    </xs:complexType>
  </xs:element>

  <xs:element name="global">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="type:type" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="attributes" type="zcl:AttributeList" minOccurs="0" maxOccurs="1" />
        <xs:element name="commands" type="zcl:CommandList" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
      <xs:attribute ref="xml:base" />
    </xs:complexType>
  </xs:element>

  <xs:element name="library">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="type:type" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="zcl:global" minOccurs="1" maxOccurs="1" />
        <xs:choice minOccurs="1" maxOccurs="unbounded">
          <xs:element ref="zcl:cluster" />
          <xs:element ref="zcl:derivedCluster" />
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
    <!-- Type Requirements -->
    <xs:keyref name="attributeDataTypeRef" refer="zcl:dataType">
      <xs:selector
        xpath=".//attributes/attribute" />
      <xs:field xpath="@type"></xs:field>
    </xs:keyref>
    <xs:keyref name="commandDataTypeRef" refer="zcl:dataType">
      <xs:selector
        xpath=".//fields/field" />
      <xs:field xpath="@type"></xs:field>
    </xs:keyref>
    <xs:keyref name="typeDataTypeFieldRef" refer="zcl:dataType">
      <xs:selector
        xpath=".//bitmap/element | .//type:sequence/field" />
      <xs:field xpath="@type"></xs:field>
    </xs:keyref>
    
    <xs:keyref name="derivedClusterNameRef" refer="zcl:clusterName">
      <xs:selector
        xpath=".//zcl:derivedCluster" />
      <xs:field xpath="@inheritsFrom" />
    </xs:keyref>
    <xs:key name="clusterName">
      <xs:selector xpath=".//zcl:cluster" />
      <xs:field xpath="@name" />  
    </xs:key>
    
    <xs:keyref name="tagDataTypeRef" refer="zcl:dataType">
      <xs:selector xpath=".//zcl:cluster/tags/tag" />
      <xs:field xpath="@type"></xs:field>
    </xs:keyref>
    <xs:key name="dataType">
      <xs:selector xpath=".//type:type"></xs:selector>
      <xs:field xpath="@short" />
    </xs:key>

    <xs:keyref name="typeDataTypeRef" refer="zcl:dataType">
      <xs:selector xpath=".//type:type | .//zcl:cluster/type | .//zcl:global/type" />
      <xs:field xpath="@inheritsFrom"></xs:field>
    </xs:keyref>
    
    <xs:unique name="picsCode">
      <xs:selector xpath=".//zcl:cluster/classification | .//zcl:derivedCluster/classification" />
      <xs:field xpath="@picsCode" />
    </xs:unique>
  </xs:element>
</xs:schema>

=== csa-iot/data-model/LevelControlForLighting.xml
<?xml version="1.0"?>
<!-- 
Zigbee Alliance owns the copyright to the text and content displayed or 
included in this document (including in PDF, XML files and other formats) in 
all forms of media, which copyright is protected by the copyright laws of the 
United States and by international treaties.  Full text of licensing terms 
applicable to this document can be found in the LICENSE.md file.
-->
<zcl:derivedCluster
  xmlns:zcl="http://zigbee.org/zcl/clusters"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:type="http://zigbee.org/zcl/types"
  xmlns:xi="http://www.w3.org/2001/XInclude"
  xsi:schemaLocation="http://zigbee.org/zcl/clusters cluster.xsd http://zigbee.org/zcl/types type.xsd"
  id="0008" revision="2" name="LevelControlForLighting" inheritsFrom="Level">
  <classification picsCode="LC" />
  <server>
    <attributes>
      <attribute ref="CurrentLevel">
        <restriction>
          <type:minInclusive value="01" />
          <type:maxInclusive value="fe" />
        </restriction>
      </attribute>
      <attribute ref="MinFrequency" requiredIf="implements(CurrentFrequency)" />
      <attribute ref="MaxFrequency" requiredIf="implements(CurrentFrequency)" />
      <attribute ref="Options" required="true" />
    </attributes>
  </server>
</zcl:derivedCluster>

=== csa-iot/data-model/unprocessed/GenericTunnel.xml
<?xml version="1.0"?>
<!-- 
Zigbee Alliance owns the copyright to the text and content displayed or 
included in this document (including in PDF, XML files and other formats) in 
all forms of media, which copyright is protected by the copyright laws of the 
United States and by international treaties.  Full text of licensing terms 
applicable to this document can be found in the LICENSE.md file.
-->
<zcl:cluster xmlns:zcl="http://zigbee.org/zcl/clusters"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:type="http://zigbee.org/zcl/types"
  xmlns:xi="http://www.w3.org/2001/XInclude"
  xsi:schemaLocation="http://zigbee.org/zcl/clusters cluster.xsd http://zigbee.org/zcl/types type.xsd"
  id="0600" revision="0" name="Generic Tunnel">
  <classification role="application" picsCode="TUN" primaryTransaction="" />
  <server>
    <attributes>
      <attribute id="0001" name="MaximumIncomingTransferSize" type="uint16" required="true" max="65535" default="0" />
      <attribute id="0002" name="MaximumOutgoingTransferSize" type="uint16" required="true" max="65535" default="0" />
      <attribute id="0003" name="ProtocolAddress" type="octstr" writable="true" required="true" default="Null string">
        <restriction>
          <type:minLength value="0" />
          <type:maxLength value="255" />
        </restriction>
      </attribute>
    </attributes>
  </server>
</zcl:cluster>

=== csa-iot/data-model/PulseWidthModulation.xml
<?xml version="1.0"?>
<!-- 
Zigbee Alliance owns the copyright to the text and content displayed or 
included in this document (including in PDF, XML files and other formats) in 
all forms of media, which copyright is protected by the copyright laws of the 
United States and by international treaties.  Full text of licensing terms 
applicable to this document can be found in the LICENSE.md file.
-->
<zcl:derivedCluster
  xmlns:zcl="http://zigbee.org/zcl/clusters"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:type="http://zigbee.org/zcl/types"
  xmlns:xi="http://www.w3.org/2001/XInclude"
  xsi:schemaLocation="http://zigbee.org/zcl/clusters cluster.xsd http://zigbee.org/zcl/types type.xsd"
  id="001C" revision="1" name="PulseWidthModulation" inheritsFrom="Level">
  <classification picsCode="PWM" />
  <server>
    <attributes>
      <attribute ref="MinLevel" required="true" />
      <attribute ref="MaxLevel" default="100" required="true">
        <restriction>
          <type:maxInclusive value="100" />
        </restriction>
      </attribute>
      <attribute ref="CurrentFrequency" required="true" />
      <attribute ref="MinFrequency" required="true" />
      <attribute ref="MaxFrequency" required="true" />
    </attributes>
    <commands>
      <command ref="MoveToClosestFrequency" required="true" />
    </commands>
  </server>
</zcl:derivedCluster>

=== csa-iot/data-model/ConcentrationMeasurement.xml
<?xml version="1.0"?>
<!-- 
Connectivity Standards Alliance owns the copyright to the text and content displayed or
included in this document (including in PDF, XML files and other formats) in 
all forms of media, which copyright is protected by the copyright laws of the 
United States and by international treaties.  Full text of licensing terms 
applicable to this document can be found in the LICENSE.md file.
-->
<zcl:cluster xmlns:zcl="http://zigbee.org/zcl/clusters"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:type="http://zigbee.org/zcl/types"
  xmlns:xi="http://www.w3.org/2001/XInclude"
  xsi:schemaLocation="http://zigbee.org/zcl/clusters cluster.xsd http://zigbee.org/zcl/types type.xsd"
  id="040C" revision="2" name="CarbonMonoxide">
  <aliases>
      <alias id="040D" name="CarbonDioxide" />
      <alias id="040E" name="Ethylene" />
      <alias id="040F" name="EthyleneOxide" />
      <alias id="0410" name="Hydrogen" />
      <alias id="0411" name="HydrogenSulfide" />
      <alias id="0412" name="NitricOxide" />
      <alias id="0413" name="NitrogenDioxide" />
      <alias id="0414" name="Oxygen" />
      <alias id="0415" name="Ozone" />
      <alias id="0416" name="SulfurDioxide" />
      <alias id="0417" name="DissolvedOxygen" />
      <alias id="0418" name="Bromate" />
      <alias id="0419" name="Chloramines" />
      <alias id="041A" name="Chlorine" />
      <alias id="041B" name="FecalColiformAndEColi" />
      <alias id="041C" name="Fluoride" />
      <alias id="041D" name="HaloaceticAcids" />
      <alias id="041E" name="TotalTrihalomethanes" />
      <alias id="041F" name="TotalColiformBacteria" />
      <alias id="0420" name="Turbidity" />
      <alias id="0421" name="Copper" />
      <alias id="0422" name="Lead" />
      <alias id="0423" name="Manganese" />
      <alias id="0424" name="Sulfate" />
      <alias id="0425" name="Bromodichloromethane" />
      <alias id="0426" name="Bromoform" />
      <alias id="0427" name="Chlorodibromomethane" />
      <alias id="0428" name="Chloroform" />
      <alias id="0429" name="Sodium" />
      <alias id="042A" name="PM25" />
      <alias id="042B" name="Formaldehyde" />
      <alias id="042C" name="PM1" />
      <alias id="042D" name="PM10" />
      <alias id="042E" name="VolatileOrganicCompounds" />
  </aliases>
  <classification role="application" picsCode="CONC" primaryTransaction="2" />
  <server>
    <attributes>
      <attribute id="0000" name="MeasuredValue" type="single" reportRequired="true" required="true" default="NaN" >
        <restriction>
          <type:minInclusiveRef ref="MinMeasuredValue" />
          <type:maxInclusiveRef ref="MaxMeasuredValue" />
        </restriction>
       </attribute>
      <attribute id="0001" name="MinMeasuredValue" type="single" required="true" min="0" default="NaN" >
        <restriction>
          <type:maxExclusiveRef ref="MaxMeasuredValue" />
        </restriction>
       </attribute>
      <attribute id="0002" name="MaxMeasuredValue" type="single" required="true" max="1" default="NaN" >
        <restriction>
          <type:minExclusiveRef ref="MinMeasuredValue" />
        </restriction>
       </attribute>
      <attribute id="0003" name="Tolerance" type="single" />
    </attributes>
  </server>
</zcl:cluster>

=== csa-iot/data-model/PollControl.xml
<?xml version="1.0"?>
<!-- 
Zigbee Alliance owns the copyright to the text and content displayed or 
included in this document (including in PDF, XML files and other formats) in 
all forms of media, which copyright is protected by the copyright laws of the 
United States and by international treaties.  Full text of licensing terms 
applicable to this document can be found in the LICENSE.md file.
-->
<zcl:cluster xmlns:zcl="http://zigbee.org/zcl/clusters"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:type="http://zigbee.org/zcl/types"
  xmlns:xi="http://www.w3.org/2001/XInclude"
  xsi:schemaLocation="http://zigbee.org/zcl/clusters cluster.xsd http://zigbee.org/zcl/types type.xsd"
  id="0020" revision="3" name="PollControl">
  <classification role="utility" picsCode="POLL" />
  <server>
    <attributes>
      <attribute id="0000" name="CheckInInterval" type="uint32" writable="true" required="true" max="7208960" default="14400" />
      <attribute id="0001" name="LongPollInterval" type="uint32" required="true" min="4" max="7208960" default="20" />
      <attribute id="0002" name="ShortPollInterval" type="uint16" required="true" min="1" max="65535" default="2" />
      <attribute id="0003" name="FastPollTimeout" type="uint16" writable="true" required="true" min="1" max="65535" default="40" />
      <attribute id="0004" name="CheckInIntervalMin" type="uint32" default="0" />
      <attribute id="0005" name="LongPollIntervalMin" type="uint32" default="0" />
      <attribute id="0006" name="FastPollTimeoutMax" type="uint16" default="0" />
    </attributes>
    <commands>
      <command id="00" name="CheckInResponse" required="true">
        <fields>
          <field name="StartFastPolling" type="bool" />
          <field name="FastPollTimeout" type="uint16" />
        </fields>
      </command>
      <command id="01" name="FastPollStop" required="true" />
      <command id="02" name="SetLongPollInterval">
        <fields>
          <field name="NewLongPollInterval" type="uint32" />
        </fields>
      </command>
      <command id="03" name="SetShortPollInterval">
        <fields>
          <field name="NewShortPollInterval" type="uint16" />
        </fields>
      </command>
    </commands>
  </server>
  <client>
    <commands>
      <command id="00" name="CheckIn" required="true" />
    </commands>  
  </client>
</zcl:cluster>

=== csa-iot/data-model/DeviceTemperatureConfiguration.xml
<?xml version="1.0"?>
<!-- 
Zigbee Alliance owns the copyright to the text and content displayed or 
included in this document (including in PDF, XML files and other formats) in 
all forms of media, which copyright is protected by the copyright laws of the 
United States and by international treaties.  Full text of licensing terms 
applicable to this document can be found in the LICENSE.md file.
-->
<zcl:cluster xmlns:zcl="http://zigbee.org/zcl/clusters"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:type="http://zigbee.org/zcl/types"
  xmlns:xi="http://www.w3.org/2001/XInclude"
  xsi:schemaLocation="http://zigbee.org/zcl/clusters cluster.xsd http://zigbee.org/zcl/types type.xsd"
  id="0002" revision="1" name="DeviceTemperatureConfiguration">
  <classification role="utility" picsCode="DTMP" />
  <server>
    <attributes>
      <!-- Device Temperature Information -->    
      <attribute id="0000" name="CurrentTemperature" type="int16" min="-200" max="200" default="non" required="true" />
      <attribute id="0001" name="MinTempExperienced" type="int16" min="-200" max="200" default="non" />
      <attribute id="0002" name="MaxTempExperienced" type="int16" min="-200" max="200" default="non" />
      <attribute id="0003" name="OverTempTotalDwell" type="uint16" max="65535" default="0" />
      <!-- Device Temperature Settings -->          
      <attribute id="0010" name="DeviceTempAlarmMask" type="map8" writable="true" requiredIf="implements(LowTempThreshold) or implements(HighTempThreshold)" default="0">
        <bitmap>
          <element name="DeviceTemperatureTooLow" type="bool" mask="01" />
          <element name="DeviceTemperatureTooHigh" type="bool" mask="02" shiftRight="1" />
        </bitmap>
      </attribute>
      <attribute id="0011" name="LowTempThreshold" type="int16" writable="true" requiredIf="implements(LowTempDwellTripPoint)" min="-200" max="200" default="non">
          <restriction>
             <type:maxExclusiveRef ref="HighTempThreshold" />
         </restriction>
      </attribute>    
      <attribute id="0012" name="HighTempThreshold" type="int16" writable="true" requiredIf="implements(HighTempDwellTripPoint)" min="-200" max="200" default="non">
          <restriction>
            <type:minExclusiveRef ref="LowTempThreshold" />
          </restriction>
      </attribute>      
      <attribute id="0013" name="LowTempDwellTripPoint" type="uint24" writable="true" requiredIf="implements(LowTempThreshold)" max="16777215" default="non"/>
      <attribute id="0014" name="HighTempDwellTripPoint" type="uint24" writable="true" requiredIf="implements(HighTempThreshold)" max="16777215" default="non"/>
    </attributes>
  </server>
</zcl:cluster>

=== csa-iot/data-model/unprocessed/SmartEnergyMessaging.xml
<?xml version="1.0"?>
<!-- 
Connectivity Standards Alliance owns the copyright to the text and content displayed or
included in this document (including in PDF, XML files and other formats) in 
all forms of media, which copyright is protected by the copyright laws of the 
United States and by international treaties.  Full text of licensing terms 
applicable to this document can be found in the LICENSE.md file.
-->
<zcl:cluster xmlns:zcl="http://zigbee.org/zcl/clusters"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:type="http://zigbee.org/zcl/types"
  xmlns:xi="http://www.w3.org/2001/XInclude"
  xsi:schemaLocation="http://zigbee.org/zcl/clusters cluster.xsd http://zigbee.org/zcl/types type.xsd"
  id="0703" revision="0" name="Messaging (Smart Energy)">
  <classification role="application" picsCode="SEMS" primaryTransaction="" />
  <server>
    <attributes />
  </server>
  <client>
    <commands>
      <command id="00" name="GetLastMessage" required="true" />
      <command id="01" name="MessageConfirmation" required="true">
        <fields>
          <field name="MessageID" type="uint32" />
          <field name="ConfirmationTime" type="UTC" />
        </fields>
      </command>
    </commands>
  </client>
</zcl:cluster>
